from video_config import (
    PROJECT_ROOT,
    GENERATE_SCRIPT,
    CLIPS_DIR,
    OUTPUT_DIR,
    CHARACTER_DIR,
    REFERENCE_DIR,
    WIDTH,
    HEIGHT,
    SOURCE_FPS,
    FINAL_FPS,
    DEFAULT_SHOT_SECONDS,
    FRAMES_PER_SHOT,
    USE_CPU_OFFLOAD,
    BASE_SEED,
    OUTPUT_CRF,
    OUTPUT_PRESET,
    PIXEL_FORMAT,
    IMAGE_EXTENSIONS,
    CLEAN_TEMPORARY_CLIPS,

    # Qwen
    QWEN_MODEL_ID,
    QWEN_LOCAL_MODEL,
    USE_LOCAL_QWEN,
    QWEN_ALLOW_HF_FALLBACK,
    QWEN_MAX_NEW_TOKENS,
    QWEN_DO_SAMPLE,
    QWEN_TEMPERATURE,

    # References
    REFERENCE_STRENGTH,
    REFERENCE_START_FRAME,

    # Output
    FINAL_VIDEO_NAME,
)
